name: tch_appliable_core
description: Flutter core package used by Tomas Chyly & appliable.eu. Contains common functionality to get started faster & consistently.
version: 0.0.1
homepage: https://tomas-chyly.com/en/project/web-browser-detect-flutter/
repository: https://github.com/tomaschyly/tch_appliable_core
issue_tracker: https://github.com/tomaschyly/tch_appliable_core/issues

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0-nullsafety.2
  html_unescape: ^1.0.2
  shared_preferences: ^0.5.12+4
  path_provider: ^1.6.24

  http: ^0.12.2
  sqflite: ^2.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
